# Generated by Django 5.1.5 on 2025-04-03 08:46

import api.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "size",
                    models.CharField(
                        validators=[api.validators.friendliness_text_validate]
                    ),
                ),
                (
                    "frenliness",
                    models.IntegerField(verbose_name=[api.validators.range_validate]),
                ),
                (
                    "trainability",
                    models.IntegerField(validators=[api.validators.range_validate]),
                ),
                (
                    "shedding_amount",
                    models.IntegerField(validators=[api.validators.range_validate]),
                ),
                (
                    "exersise_needs",
                    models.IntegerField(validators=[api.validators.range_validate]),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("age", models.IntegerField()),
                ("gender", models.CharField()),
                ("color", models.CharField()),
                ("favourite_food", models.CharField()),
                ("favourite_toy", models.CharField()),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breed",
                        to="api.breed",
                    ),
                ),
            ],
        ),
    ]
