version: '3.1'
services:
  django_test_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"

    restart: always
    networks:
       - custom

  web:
     build: .
     ports:
        - "8000:8000"
     depends_on:
       - django_test_db
     networks:
       - custom

networks:
   custom:
     driver: bridge





